#ifndef ERROR_CODES_H
#define ERROR_CODES_H

enum SemanticErrorCode {
    // First semantic stage error codes
    CLASSES__NAME_CLASHES_WITH_OTHER_CLASS_NAME,

    // Second semantic stage error codes
    FEATURES__NAME_CLASHES_WITH_CLASS_NAME,
    FEATURES__NAME_CLASHES_WITH_NAME_OF_SAME_CLASS_FEATURE,

    FEATURES__FORMAL_PARAM_NAME_CLASHES_WITH_CLASS_NAME,
    FEATURES__FORMAL_PARAM_NAME_CLASHES_WITH_NAME_OF_SELF_FEATURE,
    FEATURES__FORMAL_PARAM_NAME_CLASHES_WITH_NAME_OF_SAME_CLASS_FEATURE,
    FEATURES__FORMAL_PARAM_NAME_CLASHES_WITH_NAME_OF_OTHER_FORMAL_PARAM,

    FEATURES__LOCAL_VAR_NAME_CLASHES_WITH_CLASS_NAME,
    FEATURES__LOCAL_VAR_NAME_CLASHES_WITH_NAME_OF_SELF_FEATURE,
    FEATURES__LOCAL_VAR_NAME_CLASHES_WITH_NAME_OF_SAME_CLASS_FEATURE,
    FEATURES__LOCAL_VAR_NAME_CLASHES_WITH_NAME_OF_FORMAL_PARAM,
    FEATURES__LOCAL_VAR_NAME_CLASHES_WITH_NAME_OF_OTHER_LOCAL_VAR,

    FEATURES__FEATURE_INVALID_TYPE,
    FEATURES__FORMAL_PARAM_INVALID_TYPE,
    FEATURES__LOCAL_VAR_INVALID_TYPE,

    // Third semantic stage error codes ...
    // ... Global error codes
    INHERITANCE__UNKNOWN_PARENT,
    INHERITANCE__INHERIT_CYCLE,
    FEATURES__NAME_CLASHES_WITH_NAME_OF_INHERITED_FEATURE,

    // ... Rename error codes
    INHERITANCE__TWO_OR_MORE_RENAMES_OF_SAME_FEATURE,
    INHERITANCE__RENAME_UKNOWN_FEATURE,

    // ... Redefine error codes
    INHERITANCE__REDEFINE_CLAUSE_FEATURE_DUPLICATED,
    INHERITANCE__REDEFINE_UNKNOWN_FEATURE,
    INHERITANCE__REDEFINE_WITHOUT_REDEFINING_IN_CLASS,
    INHERITANCE__NONCONFORMING_REDEFINE,

    // ... Select error codes
    INHERITANCE__SELECT_CLAUSE_FEATURE_DUPLICATED,
    INHERITANCE__SELECT_UNKNOWN_FEATURE,
    INHERITANCE__IMPROPER_SELECT,
    INHERITANCE__REPEATEDLY_INHERITED_FEATURE_VERSIONS_CONFLICT,

    // ... Creators error codes
    CREATORS__UNKNOWN_CREATOR,
    CREATORS__SEVERAL_CREATORS_WITH_SAME_NAME,
    CREATORS__ATTRIBUTE_IS_CREATOR,
    CREATORS__CREATOR_HAS_RETURN_VALUE,
    CREATORS__MAIN_CLASS_WITHOUT_MAIN_FUNCTION,

    // Fourth semantic stage error codes
    PROGRAM__MAIN_CLASS_ISNT_SET,

    // ... Create instruction
    INSTR_CREATE__FIELD_OR_LOCAL_WITH_UNKNOWN_ID,
    INSTR_CREATE__CALL_REMOVED_DEFAULT_CREATOR,
    INSTR_CREATE__UNKNOWN_CREATOR,

    // ... Assign instruction
    INSTR_ASSIGN__FIELD_OR_LOCAL_WITH_UNKNOWN_ID,
    INSTR_ASSIGN__ROUTINE_ASSIGNMENT,
    INSTR_ASSIGN__CANT_CAST_EXPR_TO_TYPE_OF_ATTRIBUTE,
    INSTR_ASSIGN__CANT_CAST_EXPR_TO_TYPE_OF_LOCAL,

    // ... If instruction
    INSTR_IF__CONDITION_ISNT_BOOLEAN,

    // ... Loop instruction
    INSTR_LOOP__CONDITION_ISNT_BOOLEAN,

    // ... Expression as instruction
    INSTR_AS_EXPR__INSTRUCTION_RETURNS_SOME_VALUE,

    EXPR__METHOD_OR_VAR_CALL_WITH_UNKNOWN_ID,
    EXPR__SUBCALL_WITH_PRIMITIVE_TYPE_OR_VOID_OPERAND,
    EXPR__SUBCALL_WITH_NONPARENTHESIZED_CREATE_EXPR_OPERAND,
    EXPR__CALL_INVALID_ARGUMENTS_COUNT,
    EXPR__CALL_ATTRIBUTE_AS_ROUTINE,
    EXPR__CALL_NONCONFORMING_ARGUMENTS_SEQUENCE,

    EXPR__CALL_NONEXISTENT_PRECURSOR,
    EXPR__AMBIGIOUS_CALL_PRECURSOR,
    EXPR__CALL_PRECURSOR_OF_UNKNOWN_PARENT,

    EXPR__CALL_REMOVED_DEFAULT_CREATOR,
    EXPR__CALL_UNKNOWN_CREATOR_METHOD,
    EXPR__INVALID_TYPE_IN_CREATE_EXPR,

    // ... Operators ...
    // ... ... Array element access
    EXPR_ARRAY_ELEMENT_ACCESS__GETTING_ELEMENT_OF_NON_ARRAY_OBJECT,
    EXPR_ARRAY_ELEMENT_ACCESS__ELEMENT_INDEX_ISNT_INTEGER_NUMBER,
};

#endif // ERROR_CODES_H
