/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 131
#define YY_END_OF_BUFFER 132
static yyconst short int yy_accept[438] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      132,  130,  129,  127,    9,    8,  123,  124,  102,  100,
      121,  101,  116,  130,    3,    3,  122,  117,  108,  105,
      107,  118,  104,  119,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  125,  126,   12,   43,   15,  131,   44,   12,
       49,   50,   48,   14,   13,   12,   12,   13,   12,   12,
       12,   13,   12,  129,    0,    0,  128,    3,    3,  103,
      106,    0,    0,    0,    7,    0,  111,  110,  109,   56,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,

      120,   71,  120,  120,  120,  120,  120,  120,   57,  120,
      120,  120,  120,  113,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,   53,   12,   15,   41,   32,   30,
       31,   33,   34,   41,   35,   36,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       46,   46,    0,   32,   30,   31,   33,   34,   46,   35,
       36,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   14,   13,   12,   12,    0,
       12,   12,   12,    0,   13,    0,   51,   12,   12,    0,
       12,   12,   12,    0,   13,    0,   54,    0,   11,    0,

       10,  128,    3,    4,    5,    6,  120,  112,  120,  120,
      120,  120,  120,  120,  120,  120,  120,   72,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      114,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  115,    0,    0,   42,    0,    0,   45,    0,
        0,   47,    0,    0,   12,   52,    0,   12,   55,    0,
        0,    0,    0,  120,  120,  120,  120,  120,  120,  120,
      120,  120,   59,  120,  120,  120,  120,  120,   64,  120,
      120,  120,  120,  120,   63,  120,   80,  120,  120,  120,
      120,  120,   58,    1,  120,  120,   85,   62,   37,    0,

        0,    0,    0,   37,    0,    0,    0,    0,   52,   55,
        4,    5,    6,   66,  120,  120,  120,   68,  120,  120,
      120,  120,  120,  120,  120,  120,    2,  120,  120,  120,
      120,  120,   79,  120,  120,  120,   83,  120,  120,   65,
      120,    0,    0,    0,    0,    0,    0,    0,    0,  120,
      120,  120,  120,   69,  120,  120,   60,   73,  120,   75,
      120,  120,  120,  120,  120,  120,  120,   82,  120,   99,
      120,   38,    0,   39,    0,   40,    0,   38,    0,   39,
        0,   40,    0,  120,   89,  120,  120,  120,  120,  120,
       76,   77,   61,  120,  120,  120,   81,  120,   84,    0,

        0,    0,    0,    0,    0,  120,  120,  120,   70,  120,
       74,  120,  120,  120,   87,   67,   90,  120,  120,    0,
        0,    0,   91,   78,    0,    0,    0,   95,   88,   86,
       92,   93,   94,   96,   97,   98,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    5,    1,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   20,   22,   23,   24,   25,   26,
       27,   28,    1,    1,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   42,   43,   44,   45,   46,   47,
       48,   49,   50,   51,   52,   53,   54,   55,   56,   42,
       29,   30,   31,    1,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   42,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   42,   57,    1,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[59] =
    {   0,
        1,    1,    2,    3,    4,    5,    1,    1,    1,    1,
        1,    6,    1,    1,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    1,    1,    1,    1,    1,    1,    1,
        1,    8,    9,    9,    9,    9,    9,    9,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    1,    1
    } ;

static yyconst short int yy_base[456] =
    {   0,
        0,    0,   56,   60,   64,   68,   72,   77,   81,   86,
     1217, 1218, 1214, 1218,   64, 1218, 1218, 1218, 1218, 1218,
     1218,   82, 1218,   81,   84,   88, 1188, 1218, 1187, 1218,
     1186, 1218, 1218, 1208, 1157,   56,   52,   82,   78,   59,
       96,   89,   57,  107,   92,   72,   93,  108,  104,  118,
       83,  106, 1218, 1206,    0, 1218, 1205,  169, 1218,    0,
     1218, 1218,  222, 1202,  162,  279,  284,  289,  294,  180,
      185,  299,  304, 1205,  152,  167,    0,    0,    0, 1218,
     1218,    0,  163,  296, 1152,    0, 1218, 1218, 1218, 1218,
     1151, 1149,  139,  127,  105,  142,  138,  161,  154,  270,

      280, 1141,  156,  286,   58,  278,  287,  273, 1140,  303,
      304,  272,  274, 1134,  311,  291,  233,  292,  147,  297,
      295,  159,  318,  314, 1218,    0, 1181, 1218, 1218, 1218,
     1218, 1218, 1218,  361, 1218, 1218, 1218, 1218, 1218, 1218,
     1218, 1218, 1218, 1218, 1218, 1218, 1218, 1218, 1218, 1218,
     1218,  364,  383, 1218, 1218, 1218, 1218, 1218,  377, 1218,
     1218, 1218, 1218, 1218, 1218, 1218, 1218, 1218, 1218, 1218,
     1218, 1218, 1218, 1218, 1218, 1176,  398,  403,  358,  368,
      408,  413,  418,  372,  429,  425,  434,  436,  419,  441,
      443,  449,  454,  437,  491,  460,  467,  475, 1218,  479,

     1218,    0, 1141,  473,  491, 1123,  357, 1083,  403,  430,
      450,  425,  466,  392,  449,  467,  464, 1074,  462,  482,
      475,  473,  486,  465,  479,  480,  498,  499,  488,  485,
      501,  489,  492,  496,  514,  507,  504,  517,  510,  515,
      521,  518, 1068, 1107,  562, 1106,  572,  562, 1218, 1105,
      614, 1062,  624,  564, 1071,  557, 1070, 1069,  571, 1068,
      550,  593,    0,  551,  562,  611,  567,  568,  616,  516,
      571,  352,  609,  603,  606,  612,  617,  572, 1017,  613,
      618,  614,  615,  630, 1015,  626, 1014,  633,  634,  622,
      632,  637, 1013, 1012,  640,  652, 1011, 1010, 1049,  693,

      681,  684,  703, 1048,  728,  713,  738,  746, 1218, 1218,
      755,  757, 1029, 1006,  751,  753,  755, 1005,  681,  754,
      739,  752,  756,  758,  760,  638, 1004,  748,  757,  764,
      763,  762, 1003,  768,  766,  639, 1002,  771,  774, 1001,
      776,  817,  827,  846,  812,  865,  836,  884,  813,  679,
      801,  802,  815, 1000,  817,  837,  999,  998,  820,  997,
      821,  822,  838,  770,  839,  852,  840,  996,  856,  995,
      857, 1034,  898, 1033,  903, 1032,  910, 1029,  920, 1028,
      935, 1022,  942,  886,  981,  929,  933,  793,  934,  935,
      979,  959,  943,  937,  927,  938,  920,  936,  888,  970,

      989,  968,  979, 1008,  982,  961,  963,  976,  885,  977,
      861, 1016,  887, 1023,  855,  842,  836,  962,  964,  802,
      717,  713, 1218,  569,  541,  473,  446, 1218,  310,  279,
     1218, 1218, 1218, 1218, 1218, 1218, 1218, 1077, 1086, 1095,
     1104, 1108, 1108, 1117, 1126, 1135, 1144, 1153, 1162, 1171,
      290, 1174, 1183, 1192, 1195
    } ;

static yyconst short int yy_def[456] =
    {   0,
      437,    1,  438,  438,  439,  439,  438,  440,  438,  441,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  442,  437,  437,  442,  442,  437,  437,  437,  437,
      437,  437,  437,  437,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  437,  437,  444,  437,  437,  445,  437,  444,
      437,  437,  437,  437,  437,  446,  446,  447,  446,  448,
      448,  449,  448,  437,  437,  437,  450,   25,   26,  437,
      437,  451,  437,  437,  437,  452,  437,  437,  437,  437,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,

      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  437,  444,  437,  437,  437,  437,
      437,  437,  437,  453,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  454,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  446,  444,  447,
      446,  446,  446,  437,  447,  447,  447,  448,  444,  449,
      448,  448,  448,  437,  449,  449,  449,  437,  437,  437,

      437,  450,  451,  437,  437,  452,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  453,  453,  453,  453,  247,  437,  454,
      454,  454,  454,  253,  444,  447,  437,  444,  449,  437,
      437,  437,  455,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  453,  453,

      453,  453,  453,  454,  454,  454,  454,  454,  437,  437,
      437,  437,  455,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  453,  453,  453,  303,  454,  454,  454,  308,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  453,  453,  453,  453,  453,  303,  454,  454,  454,
      454,  454,  308,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  453,

      453,  377,  454,  454,  383,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  437,
      437,  437,  437,  443,  437,  437,  437,  437,  443,  443,
      437,  437,  437,  437,  437,  437,    0,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437
    } ;

static yyconst short int yy_nxt[1277] =
    {   0,
       12,   13,   14,   15,   12,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   26,   26,   26,   26,
       26,   26,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   35,   35,
       42,   35,   43,   35,   44,   45,   35,   35,   46,   47,
       48,   49,   50,   51,   52,   35,   53,   54,   56,   57,
       58,   59,   56,   57,   58,   59,   61,   62,   63,   64,
       61,   62,   63,   64,   65,   65,   65,   65,   67,   65,
       68,   68,   68,   65,   65,   65,   65,   71,   65,   72,
       72,   72,   75,   77,   80,  437,   78,   96,   93,  437,

       94,  103,  111,  104,  220,   92,   95,   81,  115,   92,
       92,   92,   92,  105,  101,   82,   73,   83,   84,   82,
       76,   97,  123,  102,   98,   92,  109,   99,  106,  116,
      100,   92,  107,  110,   69,   92,   92,   85,   86,  112,
      114,   85,   92,  117,  108,   92,   92,  118,  120,   92,
      121,  124,  113,  198,  199,  209,  119,   92,   92,   92,
       92,   92,  208,  122,  177,  177,  177,  177,  200,  201,
      211,   92,  129,  130,  131,  132,  133,  204,  204,  207,
       92,  189,  134,  190,  190,  190,  192,  210,  190,  190,
      190,   92,   92,  212,  135,   92,  136,  213,  238,  241,

       92,  137,  138,  139,  140,  217,  141,   92,  142,   92,
      191,  143,   92,  144,   92,  193,  145,  146,  147,  148,
      149,  150,  151,  152,  153,  154,  155,  156,  157,  158,
      151,  151,  151,  151,  151,  159,  151,  151,  151,  151,
      151,  151,  151,  151,  151,  151,  151,  160,  151,  161,
      151,  151,  151,  151,  162,  163,  164,  165,  151,  166,
      151,  167,  151,  151,  168,  151,  169,  151,  151,  170,
      171,  172,  173,  174,  175,  151,  151,  151,  151,  151,
      179,  236,  180,  180,  180,  182,   92,  180,  180,  180,
      184,  177,  185,  185,  185,  179,  203,  187,  180,  180,

      194,  177,  195,  195,  195,  189,  214,  197,  190,  190,
      205,  205,  205,  205,  205,  205,  205,  215,  223,  222,
      221,  218,  230,   92,  231,   92,   92,   92,  237,  196,
      216,   92,   92,   92,  191,  219,  181,  235,  228,   92,
       92,  183,  224,  240,   92,   92,  186,  239,   92,  229,
       92,  181,  225,  226,  242,  227,   92,   92,  232,  179,
      233,  234,  243,   92,   92,  153,  153,   92,  249,  184,
      437,   92,  245,  184,  246,  247,  248,  248,  248,  248,
      248,  248,  248,  248,  153,  153,  322,  249,  251,  264,
      252,  253,  254,  254,  254,  254,  254,  254,  254,  254,

      177,  177,  177,  177,  179,   92,  180,  180,  180,  179,
       92,  256,  180,  180,  182,  255,  180,  180,  180,  179,
      189,  187,  180,  180,  270,  186,  184,  437,  256,  257,
      184,  177,  185,  185,  185,  184,  437,  189,  194,  190,
      190,  190,  194,  437,  189,   92,  259,  190,  190,  258,
      192,  265,  190,  190,  190,  189,   92,  197,  190,  190,
      181,  194,  437,  259,  436,  181,  191,  260,  194,  437,
      183,  196,  266,  191,  268,  181,  198,  199,   92,  193,
      200,  201,  186,   92,  191,  271,  186,  204,  204,  435,
      196,  186,  194,  177,  195,  195,  195,  196,  267,  272,

      273,  280,   92,   92,  261,  205,  205,  205,  205,  205,
      205,  205,  269,  274,  275,   92,  282,   92,   92,   92,
       92,  196,  262,  278,  277,  281,   92,  276,   92,  279,
      283,  284,   92,   92,  285,   92,  286,  287,   92,   92,
      288,   92,   92,  289,  290,   92,  291,  292,  293,   92,
      295,   92,   92,  294,   92,  296,  297,   92,  184,  437,
       92,  434,  298,   92,  311,  311,  320,   92,   92,   92,
       92,   92,  194,  437,   92,  246,  247,  248,  248,  248,
      248,  248,  248,  248,  248,  299,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  244,  244,  250,  250,  317,

      314,  196,  315,  300,   92,  301,  302,  312,  312,  312,
      312,  312,  312,  312,  186,   92,  244,  318,  250,  321,
       92,   92,   92,  328,   92,   92,  303,  252,  253,  254,
      254,  254,  254,  254,  254,  254,  254,  304,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  316,  319,  323,
      325,  324,  331,  327,  330,  305,   92,  306,  307,   92,
      326,  329,   92,  332,   92,   92,   92,   92,   92,   92,
       92,   92,  333,  335,  334,   92,  336,  337,  308,   92,
      338,  339,  340,   92,  341,   92,   92,   92,  360,  368,
       92,   92,   92,   92,  246,  343,  343,  246,  344,  344,

      344,  344,  344,  344,  344,   92,  246,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  246,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  252,  347,  347,  353,
      384,  433,   92,  432,   92,  345,  345,  345,  345,  345,
      345,  252,  346,  346,  346,  346,  346,  346,  346,  346,
      346,  252,  348,  348,  348,  348,  348,  348,  348,  252,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  311,
      311,  312,  312,  312,  312,  312,  312,  312,  349,  349,
      349,  349,  349,  349,  350,  351,  261,  355,  262,  352,
      354,  356,   92,  357,  358,  359,  361,  362,  363,  364,

      366,   92,  365,  369,   92,   92,   92,   92,   92,   92,
       92,   92,  370,   92,  367,   92,   92,   92,  394,   92,
      371,   92,  431,   92,   92,  376,  382,   92,  409,   92,
      299,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      372,  343,  343,  377,  383,  385,   92,  387,  300,  378,
      347,  347,  386,  388,   92,   92,  390,  391,  373,  374,
      344,  344,  344,  344,  344,  344,  344,  379,   92,  389,
       92,  395,  392,   92,   92,   92,  397,  375,  304,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  393,   92,
       92,   92,   92,   92,  396,   92,  305,  380,  348,  348,

      348,  348,  348,  348,  348,   92,  398,  399,   92,   92,
       92,  246,  400,  400,   92,  381,  246,  401,  401,  401,
      401,  401,  401,  401,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  252,  403,  403,  406,  424,   92,   92,
       92,   92,  402,  402,  402,  402,  402,  402,  252,  404,
      404,  404,  404,  404,  404,  404,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  407,  408,  410,  412,  414,
      411,  413,  415,   92,  405,  405,  405,  405,  405,  405,
       92,  376,   92,  372,  400,  400,   92,   92,   92,   92,
       92,   92,  378,  403,  403,  382,   92,  416,  429,  377,

      430,  373,  374,  401,  401,  401,  401,  401,  401,  401,
      379,  417,   92,  383,   92,   92,   92,   92,  418,  419,
      375,  380,  404,  404,  404,  404,  404,  404,  404,   92,
       92,  420,   92,  421,   92,  252,  422,  423,  425,  381,
      426,  252,  252,  427,  428,  246,  246,  246,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
      263,  252,  246,   92,   92,   92,   92,   92,   92,   92,
       92,  310,  310,  309,  309,  252,   92,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   66,   66,   66,   66,   66,

       66,   66,   66,   66,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   79,   79,   91,   91,  126,  252,  246,
      246,   92,  126,  126,  126,  126,  128,   92,  128,  128,
      128,  128,  128,  128,  128,  178,   92,  178,  178,  178,
      178,  178,  178,  178,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  188,  263,  188,  188,  188,  188,  188,
      188,  188,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  202,   82,  202,  202,  202,  202,  202,  202,  202,
      206,  176,  206,  244,  127,  244,  244,   92,  244,  244,
      244,  244,  250,   92,   92,  250,  250,  250,  250,  250,

      250,  313,   92,  313,   92,   85,   74,  176,  127,  125,
       92,   90,   89,   88,   87,   74,  437,   11,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437
    } ;

static yyconst short int yy_chk[1277] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    4,    4,    4,    4,    5,    5,    5,    5,
        6,    6,    6,    6,    7,    7,    7,    7,    8,    8,
        8,    8,    8,    9,    9,    9,    9,   10,   10,   10,
       10,   10,   15,   22,   24,   25,   22,   37,   36,   26,

       36,   40,   43,   40,  105,   37,   36,   24,   46,   36,
       43,  105,   40,   40,   39,   25,   10,   25,   25,   26,
       15,   38,   51,   39,   38,   46,   42,   38,   41,   47,
       38,   39,   41,   42,    8,   38,   51,   25,   25,   44,
       45,   26,   42,   47,   41,   45,   47,   48,   49,   41,
       50,   52,   44,   75,   75,   95,   48,   49,   95,   52,
       44,   48,   94,   50,   65,   65,   65,   65,   76,   76,
       97,   50,   58,   58,   58,   58,   58,   83,   83,   93,
       94,   70,   58,   70,   70,   70,   71,   96,   71,   71,
       71,   97,   93,   98,   58,   96,   58,   99,  119,  122,

      119,   58,   58,   58,   58,  103,   58,   99,   58,  103,
       70,   58,  122,   58,   98,   71,   58,   58,   58,   58,
       58,   58,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       66,  117,   66,   66,   66,   67,  117,   67,   67,   67,
       68,   68,   68,   68,   68,   69,  451,   69,   69,   69,

       72,   72,   72,   72,   72,   73,  100,   73,   73,   73,
       84,   84,   84,   84,   84,   84,   84,  101,  108,  107,
      106,  104,  112,  100,  113,  112,  108,  113,  118,   72,
      101,  106,  430,  101,   73,  104,   66,  116,  111,  104,
      107,   67,  110,  121,  116,  118,   68,  120,  121,  111,
      120,   69,  110,  110,  123,  110,  110,  111,  115,  179,
      115,  115,  124,  429,  115,  152,  152,  124,  152,  180,
      180,  123,  134,  184,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  153,  153,  272,  153,  159,  207,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,

      177,  177,  177,  177,  178,  272,  178,  178,  178,  181,
      207,  181,  181,  181,  182,  179,  182,  182,  182,  183,
      189,  183,  183,  183,  214,  180,  186,  186,  186,  184,
      185,  185,  185,  185,  185,  187,  187,  188,  194,  188,
      188,  188,  190,  190,  191,  214,  191,  191,  191,  189,
      192,  209,  192,  192,  192,  193,  209,  193,  193,  193,
      178,  196,  196,  196,  427,  181,  188,  194,  197,  197,
      182,  190,  210,  191,  212,  183,  198,  198,  212,  192,
      200,  200,  186,  210,  193,  215,  185,  204,  204,  426,
      196,  187,  195,  195,  195,  195,  195,  197,  211,  216,

      217,  224,  215,  211,  204,  205,  205,  205,  205,  205,
      205,  205,  213,  219,  220,  219,  226,  217,  224,  213,
      216,  195,  205,  222,  221,  225,  222,  220,  221,  223,
      227,  228,  225,  226,  229,  220,  230,  231,  230,  223,
      232,  229,  232,  233,  234,  233,  235,  236,  237,  234,
      239,  227,  228,  238,  231,  240,  241,  237,  256,  256,
      236,  425,  242,  239,  261,  261,  270,  235,  240,  270,
      238,  242,  259,  259,  241,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  248,  248,  254,  254,  267,

      264,  259,  265,  247,  264,  247,  247,  262,  262,  262,
      262,  262,  262,  262,  256,  265,  248,  268,  254,  271,
      267,  268,  424,  278,  271,  278,  247,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  266,  269,  273,
      275,  274,  282,  277,  281,  253,  274,  253,  253,  275,
      276,  280,  273,  283,  266,  276,  280,  282,  283,  269,
      277,  281,  284,  288,  286,  290,  289,  290,  253,  286,
      291,  292,  295,  284,  296,  291,  288,  289,  326,  336,
      292,  326,  336,  295,  301,  301,  301,  302,  302,  302,

      302,  302,  302,  302,  302,  296,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  306,  306,  306,  319,
      350,  422,  350,  421,  319,  303,  303,  303,  303,  303,
      303,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  307,  307,  307,  307,  307,  307,  307,  307,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  311,
      311,  312,  312,  312,  312,  312,  312,  312,  308,  308,
      308,  308,  308,  308,  315,  316,  311,  321,  312,  317,
      320,  322,  321,  323,  324,  325,  328,  329,  330,  331,

      334,  328,  332,  338,  315,  322,  316,  320,  317,  323,
      329,  324,  339,  325,  335,  332,  331,  330,  364,  335,
      341,  334,  420,  364,  338,  345,  349,  339,  388,  341,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      343,  343,  343,  345,  349,  351,  388,  353,  342,  347,
      347,  347,  352,  355,  351,  352,  359,  361,  343,  344,
      344,  344,  344,  344,  344,  344,  344,  347,  353,  356,
      355,  365,  362,  359,  361,  362,  367,  344,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  363,  417,
      356,  363,  365,  367,  366,  416,  346,  348,  348,  348,

      348,  348,  348,  348,  348,  366,  369,  371,  415,  369,
      371,  373,  373,  373,  411,  348,  375,  375,  375,  375,
      375,  375,  375,  375,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  379,  379,  379,  384,  413,  409,  384,
      413,  399,  377,  377,  377,  377,  377,  377,  381,  381,
      381,  381,  381,  381,  381,  381,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  386,  387,  389,  394,  396,
      390,  395,  398,  397,  383,  383,  383,  383,  383,  383,
      395,  402,  386,  400,  400,  400,  387,  389,  390,  398,
      394,  396,  403,  403,  403,  405,  393,  406,  418,  402,

      419,  400,  401,  401,  401,  401,  401,  401,  401,  401,
      403,  407,  392,  405,  406,  418,  407,  419,  408,  410,
      401,  404,  404,  404,  404,  404,  404,  404,  404,  408,
      410,  412,  391,  412,  385,  382,  412,  412,  414,  404,
      414,  380,  378,  414,  414,  376,  374,  372,  370,  368,
      360,  358,  357,  354,  340,  337,  333,  327,  318,  314,
      313,  304,  299,  298,  297,  294,  293,  287,  285,  412,
      279,  260,  258,  257,  255,  252,  414,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  440,  440,  440,  440,  440,

      440,  440,  440,  440,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  442,  442,  443,  443,  444,  250,  246,
      244,  243,  444,  444,  444,  444,  445,  218,  445,  445,
      445,  445,  445,  445,  445,  446,  208,  446,  446,  446,
      446,  446,  446,  446,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  448,  206,  448,  448,  448,  448,  448,
      448,  448,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  450,  203,  450,  450,  450,  450,  450,  450,  450,
      452,  176,  452,  453,  127,  453,  453,  114,  453,  453,
      453,  453,  454,  109,  102,  454,  454,  454,  454,  454,

      454,  455,   92,  455,   91,   85,   74,   64,   57,   54,
       35,   34,   31,   29,   27,   13,   11,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "flex.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#define CHAR 1

#define STRING 2

#define VERBATIM_STRING 3

#define STRIPSOFF_STRING 4

#line 18 "flex.l"
    #include <ctype.h>
    #include <limits.h>

    #include "utilities/char_utilities.h"
    #include "utilities/string_utilities.h"

    enum LexerErrorCode {
        NO_ERROR,
        GENERAL_ERROR,

        INVALID_CHAR_CODE
    };

    unsigned int debug_cursorLineIndex 		= 0;
    unsigned int debug_cursorColumnIndex 	= 0;

    void debug_moveCursorToNextLine() {
        debug_cursorLineIndex++;
        debug_cursorColumnIndex = 0;
    }

    void debug_moveCursorToNextCharacter(int word_length) {
        debug_cursorColumnIndex += word_length;
    }

    unsigned int error_cursorLineIndex;
    unsigned int error_cursorColumnIndex;
#line 831 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 47 "flex.l"



    // Lexer error tools
    enum LexerErrorCode lexerErrorCode = NO_ERROR;
    char lexerErrorBuffer[1024];

    int lexerErrorValue;

    int oldCursorLineIndex 		= 0;
    int oldCursorColumnIndex 	= 0;

    // Read buffers
    char read_string[1024];

    // Constraints
    unsigned int minCharCode = 0;
    unsigned int maxCharCode = 127;


#line 1006 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 438 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1218 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 67 "flex.l"
{ printf("<BOOLEAN: %d>\n", 1); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 68 "flex.l"
{ printf("<BOOLEAN: %d>\n", 0); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 70 "flex.l"
{ printf("<DECIMAL INTEGER LITERAL: value = %ld; matched string = \"%s\">\n", getDecIntFromStringWithDecInt_eiffel(yytext), yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 71 "flex.l"
{ printf("<BINARY INTEGER LITERAL: value = %ld; matched string = \"%s\">\n", getDecIntFromStringWithBinInt_eiffel(yytext), yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 72 "flex.l"
{ printf("<OCTAL INTEGER LITERAL: value = %ld; matched string = \"%s\">\n", getDecIntFromStringWithOctInt_eiffel(yytext), yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 73 "flex.l"
{ printf("<HEXADECIMAL INTEGER LITERAL: value = %ld; matched string = \"%s\">\n", getDecIntFromStringWithHexInt_eiffel(yytext), yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 75 "flex.l"
{ printf("[ LEXICAL ERROR :: Invalid value token \"%s\" in line: %d ]\n", yytext, debug_cursorLineIndex+1); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 77 "flex.l"
{
    read_string[0] = 0;
    BEGIN(CHAR);

    error_cursorLineIndex = debug_cursorLineIndex;
    error_cursorColumnIndex = debug_cursorColumnIndex;
    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 86 "flex.l"
{
    read_string[0] = 0;
    BEGIN(STRING);

    error_cursorLineIndex = debug_cursorLineIndex;
    error_cursorColumnIndex = debug_cursorColumnIndex;
    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 95 "flex.l"
{
    read_string[0] = 0;
    BEGIN(VERBATIM_STRING);

    error_cursorLineIndex = debug_cursorLineIndex;
    error_cursorColumnIndex = debug_cursorColumnIndex;
    debug_moveCursorToNextLine();
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 104 "flex.l"
{
    read_string[0] = 0;
    BEGIN(STRIPSOFF_STRING);

    error_cursorLineIndex = debug_cursorLineIndex;
    error_cursorColumnIndex = debug_cursorColumnIndex;
    debug_moveCursorToNextLine();
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 113 "flex.l"
{
                                                                    strcat(read_string, yytext);
                                                                    debug_moveCursorToNextCharacter(yyleng);
                                                                }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 118 "flex.l"
{
                                                                    strcat(read_string, yytext);

                                                                    for (int i=0; i<strlen(yytext); i++) {
                                                                        if (yytext[i] == '\n') 	{ debug_moveCursorToNextLine(); }
                                                                        else 					{ debug_moveCursorToNextCharacter(1); }
                                                                    }
                                                                }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 127 "flex.l"
{ strcat(read_string, yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 128 "flex.l"
{ strcat(read_string, yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 130 "flex.l"
{
    if (isupper(yytext[1])) {
        strcat(read_string, "@");
    }
    else {
        printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
        lexerErrorCode = GENERAL_ERROR;
    }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 142 "flex.l"
{
    if (isupper(yytext[1])) {
        strcat(read_string, "\10");
    }
    else {
        printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
        lexerErrorCode = GENERAL_ERROR;
    }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 154 "flex.l"
{
    if (isupper(yytext[1])) {
        strcat(read_string, "^");
    }
    else {
        printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
        lexerErrorCode = GENERAL_ERROR;
    }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 166 "flex.l"
{
    if (isupper(yytext[1])) {
        strcat(read_string, "$");
    }
    else {
        printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
        lexerErrorCode = GENERAL_ERROR;
    }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 178 "flex.l"
{
    if (isupper(yytext[1])) {
        strcat(read_string, "\14");
    }
    else {
        printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
        lexerErrorCode = GENERAL_ERROR;
    }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 190 "flex.l"
{
    if (isupper(yytext[1])) {
        strcat(read_string, "\\");
    }
    else {
        printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
        lexerErrorCode = GENERAL_ERROR;
    }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 202 "flex.l"
{
    if (isupper(yytext[1])) {
        strcat(read_string, "~");
    }
    else {
        printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
        lexerErrorCode = GENERAL_ERROR;
    }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 214 "flex.l"
{
    if (isupper(yytext[1])) {
        strcat(read_string, "\n");
    }
    else {
        printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
        lexerErrorCode = GENERAL_ERROR;
    }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 226 "flex.l"
{
    if (isupper(yytext[1])) {
        strcat(read_string, "`");
    }
    else {
        printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
        lexerErrorCode = GENERAL_ERROR;
    }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 238 "flex.l"
{
    if (isupper(yytext[1])) {
        strcat(read_string, "\15");
    }
    else {
        printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
        lexerErrorCode = GENERAL_ERROR;
    }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 250 "flex.l"
{
    if (isupper(yytext[1])) {
        strcat(read_string, "#");
    }
    else {
        printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
        lexerErrorCode = GENERAL_ERROR;
    }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 262 "flex.l"
{
    if (isupper(yytext[1])) {
        strcat(read_string, "\t");
    }
    else {
        printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
        lexerErrorCode = GENERAL_ERROR;
    }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 274 "flex.l"
{
    if (isupper(yytext[1])) {
        strcat(read_string, "\0");
    }
    else {
        printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
        lexerErrorCode = GENERAL_ERROR;
    }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 286 "flex.l"
{
    if (isupper(yytext[1])) {
        strcat(read_string, "|");
    }
    else {
        printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
        lexerErrorCode = GENERAL_ERROR;
    }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 298 "flex.l"
{ strcat(read_string, "%"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 299 "flex.l"
{ strcat(read_string, "\'"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 300 "flex.l"
{ strcat(read_string, "\""); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 301 "flex.l"
{ strcat(read_string, "["); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 302 "flex.l"
{ strcat(read_string, "]"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 303 "flex.l"
{ strcat(read_string, "{"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 304 "flex.l"
{ strcat(read_string, "}"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 306 "flex.l"
{
    char buffer[1024];
    strcpy(buffer, yytext+2);
    buffer[strlen(buffer)-1] = 0;

    short charCode = getDecIntFromStringWithDecInt_eiffel(buffer);

    if (charCode >= minCharCode && charCode <= maxCharCode)   	{ appendCharToStr(read_string, read_string, charCode); }
    else                                    					{ lexerErrorValue = charCode; lexerErrorCode = INVALID_CHAR_CODE; }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 319 "flex.l"
{
    char buffer[1024];
    strcpy(buffer, yytext+2);
    buffer[strlen(buffer)-1] = 0;

    short charCode = getDecIntFromStringWithBinInt_eiffel(buffer);

    if (charCode >= minCharCode && charCode <= maxCharCode)   	{ appendCharToStr(read_string, read_string, charCode); }
    else                                    					{ lexerErrorValue = charCode; lexerErrorCode = INVALID_CHAR_CODE; }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 332 "flex.l"
{
    char buffer[1024];
    strcpy(buffer, yytext+2);
    buffer[strlen(buffer)-1] = 0;

    short charCode = getDecIntFromStringWithOctInt_eiffel(buffer);

    if (charCode >= minCharCode && charCode <= maxCharCode)   	{ appendCharToStr(read_string, read_string, charCode); }
    else                                    					{ lexerErrorValue = charCode; lexerErrorCode = INVALID_CHAR_CODE; }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 345 "flex.l"
{
    char buffer[1024];
    strcpy(buffer, yytext+2);
    buffer[strlen(buffer)-1] = 0;

    short charCode = getDecIntFromStringWithHexInt_eiffel(buffer);

    if (charCode >= minCharCode && charCode <= maxCharCode)   	{ appendCharToStr(read_string, read_string, charCode); }
    else                                    					{ lexerErrorValue = charCode; lexerErrorCode = INVALID_CHAR_CODE; }

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 358 "flex.l"
{
    printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
    lexerErrorCode = GENERAL_ERROR;

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 365 "flex.l"
{
    printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
    lexerErrorCode = GENERAL_ERROR;

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 372 "flex.l"
{
    printf("[ LEXICAL ERROR :: No matching \' bracket for bracket at (line: %d, column = %d) ]\n", error_cursorLineIndex+1, error_cursorColumnIndex+1);
    lexerErrorCode = NO_ERROR;

    BEGIN(INITIAL);
    debug_moveCursorToNextLine();
}
	YY_BREAK
case YY_STATE_EOF(CHAR):
#line 380 "flex.l"
{
    printf("[ LEXICAL ERROR :: No matching \' bracket for bracket at (line: %d, column = %d) ]\n", error_cursorLineIndex+1, error_cursorColumnIndex+1);
    lexerErrorCode = NO_ERROR;

    BEGIN(INITIAL);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 387 "flex.l"
{
    if (lexerErrorCode == NO_ERROR) {
        if (strlen(read_string) == 1) {
            printf("<CHAR LITERAL: value = \'%c\'; char code = %d>\n", read_string[0], (int)read_string[0]);
        }
        else if (strlen(read_string) > 1) {
            printf("[ LEXICAL ERROR :: More than one character are placed in single brackets \'%s\' at (line: %d, column = %d) ]\n", read_string, error_cursorLineIndex+1, error_cursorColumnIndex+1);
        }
        else if (strlen(read_string) == 0) {
            printf("[ LEXICAL ERROR :: Empty character \'\' at (line: %d, column = %d) ]\n", error_cursorLineIndex+1, error_cursorColumnIndex+1);
        }
    }
    else {
        if (lexerErrorCode == INVALID_CHAR_CODE) {
            printf("[ LEXICAL ERROR :: Invalid character code (%d) at (line: %d, column = %d) ]\n", lexerErrorValue, error_cursorLineIndex+1, error_cursorColumnIndex+1);
        }

        lexerErrorCode = NO_ERROR;
    }

    BEGIN(INITIAL);

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 412 "flex.l"
{
    for (int i=0; i<strlen(yytext); i++) {
        if (yytext[i] == '\n') 	{ debug_moveCursorToNextLine(); }
        else 					{ debug_moveCursorToNextCharacter(1); }
    }
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 419 "flex.l"
{
    printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' in string at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
    lexerErrorCode = GENERAL_ERROR;

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 426 "flex.l"
{
    printf("[ LEXICAL ERROR :: Unknown escape sequence \'%s\' in string at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
    lexerErrorCode = GENERAL_ERROR;

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 433 "flex.l"
{
    printf("[ LEXICAL ERROR :: Unknown character \"%s\" in string at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
    lexerErrorCode = GENERAL_ERROR;

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 440 "flex.l"
{
    printf("[ LEXICAL ERROR :: No matching \" bracket at (line: %d, column = %d) ]\n", error_cursorLineIndex+1, error_cursorColumnIndex+1);
    BEGIN(INITIAL);

    debug_moveCursorToNextLine();
}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 447 "flex.l"
{
    printf("[ LEXICAL ERROR :: No matching \" bracket at (line: %d, column = %d) ]\n", error_cursorLineIndex+1, error_cursorColumnIndex+1);
    BEGIN(INITIAL);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 452 "flex.l"
{
    if (lexerErrorCode == NO_ERROR) {
        printf("<STRING LITERAL: value = \"%s\">\n", read_string);
    }
    else {
        lexerErrorCode = NO_ERROR;
    }

    BEGIN(INITIAL);

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 465 "flex.l"
{
    int readString_length = strlen(read_string);
    if (read_string[readString_length-1] == '\n') {
        read_string[readString_length-1] = 0;
    }

    printf("<STRING LITERAL: value = \"%s\">\n", read_string);
    BEGIN(INITIAL);

    debug_moveCursorToNextCharacter(yyleng-1);
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 477 "flex.l"
{
    printf("[ LEXICAL ERROR :: No matching <}\"> bracket for verbatim string at (line: %d, column = %d) ]\n", error_cursorLineIndex+1, error_cursorColumnIndex+1);
    BEGIN(INITIAL);

    for (int i=0; i<strlen(yytext); i++) {
        if (yytext[i] == '\n') 	{ debug_moveCursorToNextLine(); }
        else 					{ debug_moveCursorToNextCharacter(1); }
    }
}
	YY_BREAK
case YY_STATE_EOF(VERBATIM_STRING):
#line 487 "flex.l"
{
    printf("[ LEXICAL ERROR :: No matching <}\"> bracket for verbatim string at (line: %d, column = %d) ]\n", error_cursorLineIndex+1, error_cursorColumnIndex+1);
    BEGIN(INITIAL);
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 492 "flex.l"
{
    printf("[ LEXICAL ERROR :: Invalid closing bracket <}\"> for verbatim string at (line: %d, column = %d) ]\n", debug_cursorLineIndex+1, debug_cursorColumnIndex+1);

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 498 "flex.l"
{
    char buffer_word[1024];

    int readString_length = strlen(read_string);
    if (read_string[readString_length-1] == '\n') {
        read_string[readString_length-1] = 0;
    }

    // Define number of first space characters to delete in strings in each line
    int spaceChrsCountToDelete = (read_string[strlen(read_string)-1] != '\n' ? INT_MAX : 0);
    int curr_spaceChrsCountToDelete = 0;

    int currShift = 0;
    do {
        currShift += getFirstWordFromStr(read_string + currShift, buffer_word, "\n");

        curr_spaceChrsCountToDelete = 0;
        for (int i=0; i<strlen(buffer_word) && buffer_word[i] == ' '; i++) {
            curr_spaceChrsCountToDelete++;
        }

        if (buffer_word[0] == '\0') {
            printf("GOT HERE\n");
            curr_spaceChrsCountToDelete = -1;
            spaceChrsCountToDelete = 0;
        }
        else if (spaceChrsCountToDelete > curr_spaceChrsCountToDelete) {
            spaceChrsCountToDelete = curr_spaceChrsCountToDelete;
        }

    } while(read_string[currShift] != '\0' && curr_spaceChrsCountToDelete != -1);

    // Delete defined first space characters in strings in each line
    char buffer_result[1024] = "\0";

    currShift = 0;
    do {
        currShift += getFirstWordFromStr(read_string + currShift, buffer_word, "\n");
        strcat(buffer_result, buffer_word + spaceChrsCountToDelete);
    } while(read_string[currShift] != '\0');

    printf("<STRING LITERAL: value = \"%s\">\n", buffer_result);
    BEGIN(INITIAL);

    debug_moveCursorToNextCharacter(yyleng-1);
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 545 "flex.l"
{
    printf("[ LEXICAL ERROR :: No matching <]\"> bracket for strips-off string at (line: %d, column = %d) ]\n", error_cursorLineIndex+1, error_cursorColumnIndex+1);
    BEGIN(INITIAL);

    for (int i=0; i<strlen(yytext); i++) {
        if (yytext[i] == '\n') 	{ debug_moveCursorToNextLine(); }
        else 					{ debug_moveCursorToNextCharacter(1); }
    }
}
	YY_BREAK
case YY_STATE_EOF(STRIPSOFF_STRING):
#line 555 "flex.l"
{
    printf("[ LEXICAL ERROR :: No matching <]\"> bracket for strips-off string at (line: %d, column = %d) ]\n", error_cursorLineIndex+1, error_cursorColumnIndex+1);
    BEGIN(INITIAL);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 560 "flex.l"
{
    printf("[ LEXICAL ERROR :: Invalid closing bracket <]\"> for strips-off string at (line: %d, column = %d) ]\n", debug_cursorLineIndex+1, debug_cursorColumnIndex+1);

    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 566 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 567 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 568 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 569 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 570 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 571 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 572 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 573 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 574 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 576 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 577 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 578 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 579 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 580 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 581 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 582 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 583 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 584 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 585 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 586 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 587 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 588 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 589 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 590 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 591 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 592 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 593 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 594 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 595 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 597 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 598 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 599 "flex.l"
{ printf("<KEYWORD: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 601 "flex.l"
{ printf("<DATA TYPE: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 602 "flex.l"
{ printf("<DATA TYPE: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 603 "flex.l"
{ printf("<DATA TYPE: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 604 "flex.l"
{ printf("<DATA TYPE: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 605 "flex.l"
{ printf("<DATA TYPE: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 606 "flex.l"
{ printf("<DATA TYPE: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 607 "flex.l"
{ printf("<DATA TYPE: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 608 "flex.l"
{ printf("<DATA TYPE: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 609 "flex.l"
{ printf("<DATA TYPE: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 610 "flex.l"
{ printf("<DATA TYPE: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 611 "flex.l"
{ printf("<DATA TYPE: %s>\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 613 "flex.l"
{ printf("<OPERATOR: PLUS>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 614 "flex.l"
{ printf("<OPERATOR: MINUS>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 615 "flex.l"
{ printf("<OPERATOR: MULT>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 616 "flex.l"
{ printf("<OPERATOR: INTEGER DIVISION>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 617 "flex.l"
{ printf("<OPERATOR: FRACTIONAL DIVISION>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 619 "flex.l"
{ printf("<OPERATOR: EQUALITY>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 620 "flex.l"
{ printf("<OPERATOR: INEQUALITY>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 621 "flex.l"
{ printf("<OPERATOR: MORE>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 622 "flex.l"
{ printf("<OPERATOR: LESS>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 623 "flex.l"
{ printf("<OPERATOR: MORE OR EQUAL>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 624 "flex.l"
{ printf("<OPERATOR: LESS OR EQUAL>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 626 "flex.l"
{ printf("<OPERATOR: ASSIGN>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 628 "flex.l"
{ printf("<OPERATOR: AND>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 629 "flex.l"
{ printf("<OPERATOR: OR>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 630 "flex.l"
{ printf("<OPERATOR: NOT>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 631 "flex.l"
{ printf("<OPERATOR: XOR>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 633 "flex.l"
{ printf("<OPERATOR: DOT>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 634 "flex.l"
{ printf("<OPERATOR: SEMICOLON>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 635 "flex.l"
{ printf("<OPERATOR: LEFT SQUARE BRACKET>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 636 "flex.l"
{ printf("<OPERATOR: RIGHT SQUARE BRACKET>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 638 "flex.l"
{ printf("<IDENTIFIER: \"%s\">\n", yytext); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 640 "flex.l"
{ printf("<SYNTAX SIGN: COMMA>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 641 "flex.l"
{ printf("<SYNTAX SIGN: COLON>\n"); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 642 "flex.l"
{ printf("<SYNTAX SIGN: LEFT ROUND BRACKET>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 643 "flex.l"
{ printf("<SYNTAX SIGN: RIGHT ROUND BRACKET>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 644 "flex.l"
{ printf("<SYNTAX SIGN: LEFT CURLY BRACKET>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 645 "flex.l"
{ printf("<SYNTAX SIGN: RIGHT CURLY BRACKET>\n"); debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 647 "flex.l"
{ debug_moveCursorToNextLine(); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 649 "flex.l"
{ debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 650 "flex.l"
{ debug_moveCursorToNextCharacter(yyleng); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 652 "flex.l"
{
    printf("[ LEXICAL ERROR :: Unknown token \"%s\" at (line: %d, column = %d) ]\n", yytext, debug_cursorLineIndex+1, debug_cursorColumnIndex+1);
    debug_moveCursorToNextCharacter(yyleng);
}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 657 "flex.l"
ECHO;
	YY_BREAK
#line 2154 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 438 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 438 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 437);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 657 "flex.l"

